# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4483cb7db405364ecf8fcacce76320e30932a4f114bca439cff72927d4d8d349d03ec604211088b07fbfba36ad6a32cff3d17c3088cc5c516267d78ed34a71ae

test:
  secret_key_base: 61666d26a619e814885e4e0069c7073ff734738fae8f3869b001498df7748f0ea86fd1304802707e3a08c74777bab7ab247740dd1b2fc05ba6142a2b61f7cd74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
